### ISSUE TITLE
Not able to run npm run setup

### ISSUE THREAD

**Issue by technologic808** [FrontendMasters/remix-fundamentals#1]
npm ERR! Workspaces not supported for global packages

![image](https://user-images.githubusercontent.com/20627603/182406094-cb85cd37-9526-49c2-b092-6e2850330061.png)

0 verbose cli [
0 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
0 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
0 verbose cli   'prefix',
0 verbose cli   '-g'
0 verbose cli ]
1 info using npm@8.5.0
2 info using node@v16.14.2
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 2ms
5 timing config:load:file:C:\Program Files\nodejs\node_modules\npm\npmrc Completed in 4ms
6 timing config:load:builtin Completed in 4ms
7 timing config:load:cli Completed in 3ms
8 timing config:load:env Completed in 1ms
9 info found workspace root at C:\Users\venky\Documents\GitHub\remix-fundamentals
10 timing config:load:project Completed in 30ms
11 timing config:load:file:C:\Users\venky\.npmrc Completed in 1ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:C:\Users\venky\AppData\Roaming\npm\etc\npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 1ms
16 timing config:load:credentials Completed in 0ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 44ms
19 timing npm:load:configload Completed in 44ms
20 timing npm:load:setTitle Completed in 1ms
21 timing config:load:flatten Completed in 3ms
22 timing npm:load:display Completed in 4ms
23 verbose logfile C:\Users\venky\AppData\Local\npm-cache\_logs\2022-08-02T14_57_01_852Z-debug-0.log
24 timing npm:load:logFile Completed in 5ms
25 timing npm:load:timers Completed in 0ms
26 timing npm:load:configScope Completed in 0ms
27 timing npm:load Completed in 55ms
28 verbose stack Error: Workspaces not supported for global packages
28 verbose stack     at Npm.exec (C:\Program Files\nodejs\node_modules\npm\lib\npm.js:139:15)
28 verbose stack     at async module.exports (C:\Program Files\nodejs\node_modules\npm\lib\cli.js:66:5)
29 verbose cwd C:\Users\venky\Documents\GitHub\remix-fundamentals\exercise\09-env-vars
30 verbose Windows_NT 10.0.22000
31 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "prefix" "-g"
32 verbose node v16.14.2
33 verbose npm  v8.5.0
34 error Workspaces not supported for global packages
35 verbose exit 1
36 timing npm Completed in 272ms
37 verbose unfinished npm timer command:prefix 1659452222119
38 verbose code 1
39 error A complete log of this run can be found in:
39 error     C:\Users\venky\AppData\Local\npm-cache\_logs\2022-08-02T14_57_01_852Z-debug-0.log

![image](https://user-images.githubusercontent.com/20627603/182406459-8ff5e0b8-c03f-419c-acca-4c4a9fbad629.png)

this keeps happening in a loop

**Comment by technologic808** [comment]
![image](https://user-images.githubusercontent.com/20627603/182409726-eb0c6e30-b1ed-4c4d-82d1-c408769cad0c.png)
This is repeating until timeout

**Comment by 1Marc** [comment]
In chat people are saying that they had similar issues with trying to get it to run with Node.js 14. If that is the case, you need to upgrade to Node.js 16+.

**Comment by technologic808** [comment]
> In chat people are saying that they had similar issues with trying to get it to run with Node.js 14. If that is the case, you need to upgrade to Node.js 16+.

https://user-images.githubusercontent.com/20627603/182406094-cb85cd37-9526-49c2-b092-6e2850330061.png

as mentioned in the screenshot in the post, I am already using node 16+
@1Marc

**Comment by nikhilkuyya** [comment]
me facing issue : Error: Cannot find module 'esbuild' 
done : npm install esbuild to fix this.

**Comment by technologic808** [comment]
Fixed by updating node to the latest version of 16, updating Git to the latest version, and updating two strings in node based on a warning in the console
