### ISSUE TITLE
Problem with setup

### ISSUE THREAD

**Issue by VDunca** [FrontendMasters/remix-fundamentals#11]
Hi.
I have a problem with: npm run setup. It freezez before completing. (picture 1)
I have tried to abort it and run it again but then it runs in a loop and sais prism have an update. (picture 2)
Then if i abort that i cant run the exercises. (picture 3)

picture 1:
![problem installing](https://user-images.githubusercontent.com/69861117/190215039-2950a5f6-7aff-474a-96aa-ded6d055d974.png)

picture 2:
![problem installing 2](https://user-images.githubusercontent.com/69861117/190215055-c7d28fae-df9a-4ba1-9c43-0e0b90ad2e06.png)

picture 3:
![problem installing 3](https://user-images.githubusercontent.com/69861117/190215102-b33fc7a4-e1d4-4633-a967-2473187eca8f.png)

**Comment by dtauer** [comment]
We've patched the issue with Windows installation. Node version 16 is now the minimum required version.
