### ISSUE TITLE
Initial setup fails 

### ISSUE THREAD

**Issue by mustafasakalli** [FrontendMasters/remix-fundamentals#12]
Hey guys,
While I'm trying to setup project, it throws `Error: Cannot find module 'esbuild'` error. How can I fix this?
![remix](https://user-images.githubusercontent.com/23080078/193369075-ee42485b-8438-42ad-af6d-d1df4ab9eef8.png)

**Comment by Eslam3bed** [comment]
@mustafasakalli  check the `node` version if it fulfilles the [required versions][1]

[1]: https://github.com/FrontendMasters/remix-fundamentals#system-requirements

**Comment by dtauer** [comment]
@mustafasakalli can you run `node -v` in your terminal? What version of Node are you using?

**Comment by dtauer** [comment]
Recreated the issue on a windows machine that had Node v14.x.x. Updated to current LTS (16.17.1) and the setup script ran successfully. Will remove Node 14.x.x from the prerequisites.

**Comment by mustafasakalli** [comment]
Updating npm version 6 to 8 solved my problem. Thanks everyone
