### ISSUE TITLE
TypeError: Value of "this" must be of type URLSearchParams

### ISSUE THREAD

**Issue by muhammadmalik645** [FrontendMasters/remix-fundamentals#29]
I am getting this error whenever I node dev any exercise

![Screenshot 2024-09-06 195420](https://github.com/user-attachments/assets/7924c552-3d60-411d-adff-a93ce56d548f)

**Comment by aabdullaharif** [comment]
I fixed this by navigating to the exercise's directory, installing `@remix-run/web-fetch@4.3.4` with npm i, and then running the exercise again.

**Comment by fmkguy** [comment]
For me, it was an issue because I was running Node v20. Once I updated to a more recent version of Remix (still v1--`v1.19.3`--for the sake of trying not to introduce breaking changes) everything worked fine.

I found this issue helpful: https://github.com/remix-run/remix/issues/6118
