### ISSUE TITLE
Running node dev setup is leading to infinite loop 

### ISSUE THREAD

**Issue by harshith-venkatesh** [FrontendMasters/remix-fundamentals#4]
<img width="1440" alt="Screenshot 2022-08-02 at 10 31 31 PM" src="https://user-images.githubusercontent.com/44545218/182432426-ac294789-29f6-40b5-9b50-1be813e02292.png">

🏎  npm run build in /Users/harshithvenkatesh/Documents/Projects/Remix-BootCamp-FrontEnd-Masters/remix-fundamentals-bootcamp/final/05-mutations

> build
> run-s build:*

> build:css
> npm run generate:css -- --minify

> generate:css
> tailwindcss -o ./app/styles/tailwind.css "--minify"

Done in 146ms.

**Comment by Royston-Shufflebotham-i2** [comment]
Are you sure it's in an infinite loop or is it just doing a similar thing in several different directories so it _looks_ like it's repeating?

**Comment by harshith-venkatesh** [comment]
I waited for close to 5 mins, Let me check it again after the discussion.
Currently I have forcefully quit the process

**Comment by Royston-Shufflebotham-i2** [comment]
In your screenshot above it's operating on different directories. (05-mutations vs 05-mutations.extra-01-error)
It's running quite a few setup tasks in quite a few separate example directories (https://github.com/FrontendMasters/remix-fundamentals/tree/3de67525ff7b3068a94623f341a06ba48425e565/final), so could easily take 10 minutes depending on your computer speed.

**Comment by harshith-venkatesh** [comment]
It makes sense.
Thanks for clarifying
